version: "3.5"

services:
  app:
    container_name: docker-play-by-mood
    image: node:18-alpine
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn dev"
  mongodb:
    image: mongo
    container_name: docker-mongodb-play-by-mood
    ports:
      - "27018:27017"
      - "28018:28017"
